# Generated by Django 3.2 on 2021-08-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210827_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglike',
            name='like',
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
