# Generated by Django 3.2 on 2021-08-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
