# Generated by Django 3.2 on 2021-08-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210826_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='About',
        ),
    ]
